<?php


//class Shop {
//    // Область видимости private блокирует доступ к изменению значения вне класса
//    private $name;
//
//
//    // Спецификатор - protected
//
//
//    public function getName()
//    {
//        echo $this->name = "Apple";
//    }
//
//}


//class User {
////    public $name;
////    public $password;
////    public $email;
////    public $city;
////
////     Конструктор -
////    public function __construct($name,$password,$email,$city){
////        $this->name = $name;
////        $this->password = $password;
////        $this->email = $email;
////        $this->city = $city;
////    }
//
//
//    private static $name;
//
//    public static function setName($name1) {
//        self::$name = $name1;
//    }
//
//    public static function getName($name)
//    {
//        self::$name = $name;
//    }
//
//}



class Automobile {
    public $mark;
    public $model;
    public $color;
    public $country_maker;


    public function __construct($mark,$model,$color,$country_maker)
    {
        $this->mark = $mark;
        $this->model = $model;
        $this->color = $color;
        $this->country_maker = $country_maker;
    }
    // применение только внутри описания класса
    private function getInfo() {
        echo "<p style='text-align: center'>$this->mark</p>";
        echo "<p style='text-align: center'>$this->model</p>";
        echo "<p style='text-align: center'>$this->color</p>";
        echo "<p style='text-align: center'>$this->country_maker</p>";
    }


    // сдача авто в аренду
    public function AssignLease($driver_name,$date_start,$date_end) {
        $this->getInfo();
        echo "<p style='text-align: center'>Данный автомобиль будет принадлежать водителю $driver_name в период с $date_start по $date_end</p>";
    }

}

// Грузовик, наследующий свойства автомобиля
class Truck extends Automobile {

    public $load_capacity;

    public function __construct($mark, $model, $color, $country_maker,$load_capacity)
    {

        parent::__construct($mark, $model, $color, $country_maker);
        $this->load_capacity = $load_capacity;
    }

    public function AssignLease($driver_name, $date_start, $date_end)
    {
        parent::AssignLease($driver_name, $date_start, $date_end); // TODO: Change the autogenerated stub
        echo "<p style='text-align: center'>Данный автомобиль имеет грузоподъёмность $this->load_capacity</p>";
    }
}